<a href="https://colab.research.google.com/github/luucymason/python_tutorial_3_4/blob/main/own_exercises_from_intro_3_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

set up^ may need to repeat in different code boxes

SECTION 1 - FILTERING AND SELECTING DATA

Q1. Basic filtering
An online shop wants to find orders costing more than £200.
	1. Display all orders where Price is greater than 200.
	2. Display only the Product and Price columns for those orders.
Count how many orders meet this condition.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#display all orders where price is greater than 200

orders.query("Price > 200")

#display only the product and price columns for those orders

print(orders[["Product", "Price"]])

#how many orders meet this condition --> 3

#inner [] is a list of column names
#outer [] selects those columns from the dataframe

   Order_ID Customer  Product  Price  Quantity Region  Rating
0      1001    Alice   Laptop    899         1  North       5
2      1003    Chloe   Laptop    899         1  North       5
5      1006     Finn  Monitor    220         2  South       5
    Product  Price
0    Laptop    899
1     Mouse     25
2    Laptop    899
3  Keyboard     75
4     Mouse     25
5   Monitor    220

Q2. Combining conditions
Find orders where the price is at least £200 AND the customer rating is below 5.
	1. Filter using both conditions.
	2. Display Order_ID, Product, Price and Rating.
Explain why pandas uses & rather than and here.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#where is the price at least 200 and the customer rating is below 5
#filter using both conditions

orders.query("Price >= 200" and "Rating < 5")

#display order ID, product, price, rating

print(orders[["Order_ID", "Product", "Price", "Rating"]])

   Order_ID   Product  Price  Rating
0      1001    Laptop    899       5
1      1002     Mouse     25       4
2      1003    Laptop    899       5
3      1004  Keyboard     75       3
4      1005     Mouse     25       4
5      1006   Monitor    220       5

Q3. Selecting multiple possible values
A manager wants to see orders from the North and West regions.
	1. Filter using .isin().
	2. Display only Customer, Product and Region.
	3. Sort the results alphabetically by region.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#filter using .isin(), show only customer, product and region from north and west
#sort the results alphabetically by region

orders[orders["Region"].isin(["North", "West"])][["Customer", "Product", "Region"]].sort_values("Region")

  Customer   Product Region
0    Alice    Laptop  North
2    Chloe    Laptop  North
3    David  Keyboard   West

Q4. Selecting rows and columns
	1. Use .iloc to retrieve the first three rows.
	2. Retrieve the first three rows and first four columns.
	3. Use .loc to display the customers and prices of orders costing at least £200.
	4. Explain the difference between selecting a column with orders["Product"] and orders[["Product"]].

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#.iloc to get first 3 rows

orders.iloc[0:3]

#first 3 rows and 4 columns

orders.iloc[0:3, 0:4]

#.loc display customers and prices of orders costing at least 200

orders.loc[orders["Price"] >=200][["Customer", "Price"]]

#[] gives pandas series 1D single column of values, [[]] gives dataframe 2D table

  Customer  Price
0    Alice    899
2    Chloe    899
5     Finn    220

SECTION 2 - CREATING AND ANALYSING COLUMNS

Q5. Calculated columns
The business wants to calculate the revenue generated by each order.
	1. Create a Revenue column using Price × Quantity.
	2. Display the order ID, product, quantity and revenue.
Calculate total revenue across all orders.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#create revenue column using price x quantity

orders["Revenue"] = orders["Price"]*orders["Quantity"]
print(orders)

#display order ID, product, quantity and revenue

print(orders[["Order_ID", "Price", "Quantity", "Revenue"]])

#calculate total revenue across all orders

orders[["Revenue"]].sum(axis=0)

   Order_ID Customer   Product  Price  Quantity Region  Rating  Revenue
0      1001    Alice    Laptop    899         1  North       5      899
1      1002      Ben     Mouse     25         2  South       4       50
2      1003    Chloe    Laptop    899         1  North       5      899
3      1004    David  Keyboard     75         1   West       3       75
4      1005     Ella     Mouse     25         4   East       4      100
5      1006     Finn   Monitor    220         2  South       5      440
   Order_ID  Price  Quantity  Revenue
0      1001    899         1      899
1      1002     25         2       50
2      1003    899         1      899
3      1004     75         1       75
4      1005     25         4      100
5      1006    220         2      440

Revenue    2463
dtype: int64

Q6. Boolean conditions and lambda
	1. Create a High_Value column that is True when revenue exceeds £500 and False otherwise.
	2. Use .apply() and a lambda expression to create a Feedback column:
		○ Rating above 3 = "Positive"
		○ Rating of 3 or below = "Needs Review"
Display the relevant columns to check your results.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

orders["Revenue"] = orders["Price"]*orders["Quantity"]

#High_Value column when revenue is true when bigger than 500 and false if else

orders["High_Value"] = orders["Revenue"].apply(lambda x: x > 500)
print(orders)

#make feedback column with .apply and lambda where rating above 3 is positive and below 3 is needs review

orders["Feedback"] = orders["Rating"].apply(lambda x: "Positive" if x > 3 else "Needs review")
print(orders)

   Order_ID Customer   Product  Price  Quantity Region  Rating  Revenue  \
0      1001    Alice    Laptop    899         1  North       5      899
1      1002      Ben     Mouse     25         2  South       4       50
2      1003    Chloe    Laptop    899         1  North       5      899
3      1004    David  Keyboard     75         1   West       3       75
4      1005     Ella     Mouse     25         4   East       4      100
5      1006     Finn   Monitor    220         2  South       5      440

   High_Value
0        True
1       False
2        True
3       False
4       False
5       False
   Order_ID Customer   Product  Price  Quantity Region  Rating  Revenue  \
0      1001    Alice    Laptop    899         1  North       5      899
1      1002      Ben     Mouse     25         2  South       4       50
2      1003    Chloe    Laptop    899         1  North       5      899
3      1004    David  Keyboard     75         1   West       3       75
4      1005     Ella     Mouse     25         4   East       4      100
5      1006     Finn   Monitor    220         2  South       5      440

   High_Value      Feedback
0        True      Positive
1       False      Positive
2        True      Positive
3       False  Needs review
4       False      Positive
5       False      Positive

SECTION 3 - INSPECTING AND SORTING DATASETS

Q7. Inspect unfamiliar data
Using customers:
	1. Display the first three rows and last two rows.
	2. Find the dataset's shape and number of rows.
	3. Display the column names.
	4. Use .info() to inspect data types and missing values.
Use .describe() to summarise numerical data.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})

#display first 3 rows and last 2 rows

orders.head(3)
orders.tail(2)

#find datas shape and number of rows

orders.shape #shows rows and columns, so 6 rows 7 columns

#display column names

orders.columns

#use info() to inspect data types and missing values, use describe to summarise data
orders.info()
orders.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  6 non-null      int64
 1   Customer  6 non-null      object
 2   Product   6 non-null      object
 3   Price     6 non-null      int64
 4   Quantity  6 non-null      int64
 5   Region    6 non-null      object
 6   Rating    6 non-null      int64
dtypes: int64(4), object(3)
memory usage: 468.0+ bytes

          Order_ID       Price  Quantity    Rating
count     6.000000    6.000000  6.000000  6.000000
mean   1003.500000  357.166667  1.833333  4.333333
std       1.870829  425.739083  1.169045  0.816497
min    1001.000000   25.000000  1.000000  3.000000
25%    1002.250000   37.500000  1.000000  4.000000
50%    1003.500000  147.500000  1.500000  4.500000
75%    1004.750000  729.250000  2.000000  5.000000
max    1006.000000  899.000000  4.000000  5.000000

Q8. Sorting and summaries
Using orders:
	1. Sort orders by price, highest first.
	2. Sort by revenue, highest first, then rating, highest first.
	3. Display the three highest-revenue orders.
Calculate the mean, minimum and maximum prices.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#sort orders by price highest first

orders.sort_values(["Price"], ascending = False)

#sort by revenue highest first, then rating highest first

orders.sort_values(["Revenue"], ascending = False)
orders.sort_values(["Rating"], ascending = False)

#display 3 highest revenue orders, calculate mean/min/max prices

orders.nlargest(3, "Revenue")

orders["Revenue"].describe() #stats for one column

count      6.000000
mean     410.500000
std      404.243862
min       50.000000
25%       81.250000
50%      270.000000
75%      784.250000
max      899.000000
Name: Revenue, dtype: float64

SECTION 4 - CLEANING MESSY DATA

Q9. Missing values
Using customers:
	1. Count missing values in each column using .isna().sum().
	2. Display rows where Spend is missing.
	3. Create a separate DataFrame with rows containing missing values removed.
	4. In another version, fill missing spending values with zero.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#count missing values in each column using .isna().sum()

customers.isna().sum()

#display rows where spend is missing

customers[customers.isna().any(axis = 1)]
#isna() checks for missing values
#any checks where at least one value is missing
#axis=1 goes across rows

#create separate dataframe with rows containing missing values removed

customers_clean = customers.dropna()
print(customers_clean)
#dropna returns a dataframe so don't need to create one

#fill missing spending values with 0
customers_new = customers.fillna(0)
print(customers_new)

   Customer_ID  Country Age  Spend Membership
0            1       UK  22  120.5       Gold
1            2      usa  35  300.0     Silver
3            4  Germany  41  450.0     Bronze
4            5     USA   35  300.0     Silver
   Customer_ID  Country Age  Spend Membership
0            1       UK  22  120.5       Gold
1            2      usa  35  300.0     Silver
2            3      UK   28    0.0       Gold
3            4  Germany  41  450.0     Bronze
4            5     USA   35  300.0     Silver
5            6  germany  19    0.0       Gold

Q10. Standardising text and data types
	1. Remove leading and trailing spaces from Country.
	2. Convert country names to uppercase.
	3. Convert Age from text into integers using .astype(int).
	4. Calculate the average age.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#remove whitespace from country

customers["Country"] = customers["Country"].str.strip()

#convert to uppercase

customers["Country"] = customers["Country"].str.upper()

#convert age from text into integers using .astype(int)

customers["Age"] = customers["Age"].astype(int)
print(customers)

#calculate average age, chose to look at mean

customers["Age"].mean()

   Customer_ID  Country  Age  Spend Membership
0            1       UK   22  120.5       Gold
1            2      USA   35  300.0     Silver
2            3       UK   28    NaN       Gold
3            4  GERMANY   41  450.0     Bronze
4            5      USA   35  300.0     Silver
5            6  GERMANY   19    NaN       Gold

np.float64(30.0)

Q11. Duplicates and column names
	1. Create a duplicate row in a copy of customers.
	2. Count duplicates using .duplicated().sum().
	3. Remove duplicates and reset the index.
	4. Remove spaces from column names and convert them to lowercase.
Rename customer_id to id using .rename(columns={...}).

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#make duplicate row in a copy of customers (chose row 1)

customers_copy = customers.copy()
customers_copy = pd.concat(
    [customers_copy, customers_copy.iloc[[0]]],
    ignore_index = True
)


#.copy() makes a copy, iloc[[0]] selects first row as a dataframe
#pd.concat adds the duplicated row at the bottom
#nidex true resets the row index so it runs consecutively

#count duplicates using .duplicated().sum()
customers_copy.duplicated().sum()

#remove duplicates and reset index

customers_copy.drop_duplicates().reset_index(drop = True)

#remove spaces from column names and convert to lowercase
#Rename customer_id to id using .rename(columns={...})

customers.columns = customers.columns.str.strip()
customers.rename(columns={"Customer_ID": "ID"}, inplace = True)
print(customers)

   ID  Country Age  Spend Membership
0   1       UK  22  120.5       Gold
1   2      usa  35  300.0     Silver
2   3      UK   28    NaN       Gold
3   4  Germany  41  450.0     Bronze
4   5     USA   35  300.0     Silver
5   6  germany  19    NaN       Gold

SECTION 5 - MODIFYING AND COMBINING DATAFRAMES

Q12. Adding and removing columns
	1. Add a Revenue column to orders.
	2. Remove that column using .drop(columns=...).
	3. Explain why the result of .drop() must be assigned back if you want to keep the change.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#already added revenue column, now drop the column

orders = orders.drop(columns=["Revenue"])
print(orders)

#assigned back because Pandas usually creates a modified copy of Dataframe rather than changing the original one

   Order_ID Customer   Product  Price  Quantity Region  Rating
0      1001    Alice    Laptop    899         1  North       5
1      1002      Ben     Mouse     25         2  South       4
2      1003    Chloe    Laptop    899         1  North       5
3      1004    David  Keyboard     75         1   West       3
4      1005     Ella     Mouse     25         4   East       4
5      1006     Finn   Monitor    220         2  South       5

Q13. Adding new records
Create a new DataFrame containing one order:
	• Order ID: 1007
	• Customer: Grace
	• Product: Mouse
	• Price: 25
	• Quantity: 3
	• Region: West
	• Rating: 4
Combine it with orders using pd.concat() and ignore_index=True.
Then display the last three rows and the new dataset shape.

In [ ]:
import pandas as pd
import numpy as np
orders = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Customer": ["Alice", "Ben", "Chloe", "David", "Ella", "Finn"],
    "Product": ["Laptop", "Mouse", "Laptop", "Keyboard", "Mouse", "Monitor"],
    "Price": [899, 25, 899, 75, 25, 220],
    "Quantity": [1, 2, 1, 1, 4, 2],
    "Region": ["North", "South", "North", "West", "East", "South"],
    "Rating": [5, 4, 5, 3, 4, 5]
})
customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4, 5, 6],
    "Country": [" UK", "usa", "UK ", "Germany", "USA ", "germany"],
    "Age": ["22", "35", "28", "41", "35", "19"],
    "Spend": [120.5, 300.0, np.nan, 450.0, 300.0, np.nan],
    "Membership": ["Gold", "Silver", "Gold", "Bronze", "Silver", "Gold"]
})
orders["Revenue"] = orders["Price"]*orders["Quantity"]

#create new dataframe as suggested

new = pd.DataFrame({
    "Order_ID": [1007],
    "Customer": ["Grace"],
    "Product": ["Mouse"],
    "Price": [25],
    "Quantity": [3],
    "Region": ["West"],
    "Rating": [4]
})

#combine it with orders

combined = pd.concat([orders, new], ignore_index=True)
print(combined)

#made new dataset or can combine them into one already existing

orders = pd.concat([orders, new], ignore_index=True)
print(orders)

#show last 3 rows and new dataset shape

combined.tail(3)
combined.shape #7 rows, 8 columns

   Order_ID Customer   Product  Price  Quantity Region  Rating  Revenue
0      1001    Alice    Laptop    899         1  North       5    899.0
1      1002      Ben     Mouse     25         2  South       4     50.0
2      1003    Chloe    Laptop    899         1  North       5    899.0
3      1004    David  Keyboard     75         1   West       3     75.0
4      1005     Ella     Mouse     25         4   East       4    100.0
5      1006     Finn   Monitor    220         2  South       5    440.0
6      1007    Grace     Mouse     25         3   West       4      NaN
   Order_ID Customer   Product  Price  Quantity Region  Rating  Revenue
0      1001    Alice    Laptop    899         1  North       5    899.0
1      1002      Ben     Mouse     25         2  South       4     50.0
2      1003    Chloe    Laptop    899         1  North       5    899.0
3      1004    David  Keyboard     75         1   West       3     75.0
4      1005     Ella     Mouse     25         4   East       4    100.0
5      1006     Finn   Monitor    220         2  South       5    440.0
6      1007    Grace     Mouse     25         3   West       4      NaN

(7, 8)

Q14. Using axis
Using the medal dataset below:
medals = pd.DataFrame({
    "Country": ["USA", "GBR", "CHN"],
    "Gold": [46, 27, 26],
    "Silver": [37, 23, 18],
    "Bronze": [38, 17, 26]
})
	1. Create a Total column by summing the medal counts across each row using axis=1.
	2. Calculate the totals for each medal type.

In [ ]:
import pandas as pd
import numpy as np

medals = pd.DataFrame({
    "Country": ["USA", "GBR", "CHN"],
    "Gold": [46, 27, 26],
    "Silver": [37, 23, 18],
    "Bronze": [38, 17, 26]
})

#total column by summing medal counts across each row axis=1

medals["Total"] = medals[["Gold", "Silver", "Bronze"]].sum(axis=1)
print(medals)

#calculate totals for each medal type

medals[["Gold", "Silver", "Bronze"]].sum(axis=0)
#axis = 0 adds all the values down each column, =1 adds all the values across each row

  Country  Gold  Silver  Bronze  Total
0     USA    46      37      38    121
1     GBR    27      23      17     67
2     CHN    26      18      26     70

Gold      99
Silver    78
Bronze    81
dtype: int64

SECTION 6 - LOADING AND SAVING DATA

Q15. CSV files
	1. Explain the difference between installing a package using pip and importing it.
	2. Load a CSV file called sales.csv using pd.read_csv().
	3. Display its first five rows.
	4. Inspect its data types and missing values using .info().

In [ ]:
#installing with pip and importing
#install is adding it to the python environment, import is when you want to use its functions - make it available to the code

#load csv called sales.csv using pd.read_csv()
#this is a random dataset from kaggle
import pandas as pd
import numpy as np

sales = pd.read_csv("sales.csv")
sales.head() #displays first 5 words to check it worked

#inspect data types and missing values using .info()

sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          100 non-null    object
 1   Country         100 non-null    object
 2   Item Type       100 non-null    object
 3   Sales Channel   100 non-null    object
 4   Order Priority  100 non-null    object
 5   Order Date      100 non-null    object
 6   Order ID        100 non-null    int64
 7   Ship Date       100 non-null    object
 8   Units Sold      100 non-null    int64
 9   Unit Price      100 non-null    float64
 10  Unit Cost       100 non-null    float64
 11  Total Revenue   100 non-null    float64
 12  Total Cost      100 non-null    float64
 13  Total Profit    100 non-null    float64
dtypes: float64(5), int64(2), object(7)
memory usage: 11.1+ KB

SECTION 7 - PACKAGES, API AND ERRORS

Q16. Imports and modules
	1. Import math using the alias m.
	2. Calculate the square root of 144 using m.sqrt().
	3. Import datetime from the datetime module.
	4. Display the current date and time in the format YYYY-MM-DD HH:MM:SS.
Use os.getcwd() to display the current working directory.

In [ ]:
import pandas as pd
import numpy as np

import math as m #dont need pip as its built into python

#square root of 144 using m.sqrt()

m.sqrt(144) #12.0

#import datetime from datetime module

from datetime import datetime

#display current date and time in format yyyy-mm-dd hh:mm:ss
#working directory os.getcwd()

print(datetime.now().strftime("%y-%m-%d %H:%M:%S"))

import os
os.getcwd() #shows the folder python is currently working from

#for knowing how to use modules, look at official python documentation
#this is if they're part of python, not using pip install
#other ways to know what a module does

import datetime
help(datetime) #can explain functions
help(datetime.datetime.now) #explain specific functions
print(dir(datetime)) #shows all functions

26-10-15 10:21:46
Help on built-in function now:

now(tz=None) class method of datetime.datetime
    Returns new datetime object representing current time local to tz.

      tz
        Timezone object.

    If no tz is specified, uses local timezone.

Q17. Retrieve data from an API
Use the Cat Fact API: https://catfact.ninja/fact
	1. Import requests.
	2. Send a GET request to the API.
	3. Print the HTTP status code.
	4. Convert the response to a Python object using .json().
	5. Print only the cat fact rather than the entire response.
Explain what an API does and why JSON responses can be accessed using dictionary-style keys.

In [ ]:
#get data from API

import requests
url = "https://catfact.ninja/fact"
response = requests.get(url)

print(response.status_code) #200, request succeeded

#converts to python object and prints the cat fact
data = response.json()
print(data)

#API allows different software applications to communicate and exchange data like retrieving country info from a server
#JSON responses accessed with dictionary style keys, JSON objects are converted to python dictionaries letting you retrieve values using keys

200
{'fact': 'Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.', 'length': 121}

Q18. Understand and fix errors
For each example, identify the error type, explain why it occurs and correct the code.
# A
customer = {"name": "Alice", "age": 22}
print(customer["marks"])
# B
age = "22"
print(age + 5)
# C
products = ["Laptop", "Mouse", "Keyboard"]
print(products[5])
# D
price = 50
print(price.upper())
# E
print(total_revenue)
Use these error types where appropriate: KeyError, TypeError, IndexError, AttributeError and NameError.

In [ ]:
customer = {"name": "Alice", "age": 22}
print(customer["marks"])

#key error, the dictionary key doesn't exist in the dictionary

age = "22" print(age + 5)

#type error, you can't do a proper operation with a string and int

products = ["Laptop", "Mouse", "Keyboard"] print(products[5])

#index error, there are only 3 items in the list not 5, 5 doesn't exist

price = 50 print(price.upper())

#attribute error, cannot print the integer in uppercase

print(total_revenue)

#name error, the variable/name hasn't been defined beforehand

SECTION 8 = FINAL DATA-WRANGLING CHALLENGE

Run this code to create a deliberately messy dataset.
sales = pd.DataFrame({
    " Product ": ["Laptop", " Mouse", "LAPTOP", "Keyboard ",
                  "Mouse", "Monitor"],
    " Region ": ["north", "South ", "NORTH", "west",
                 "south", "West "],
    " Units ": ["2", "5", "1", "3", "5", "2"],
    " Unit_Price ": [899, 25, 899, 75, 25, 220],
    " Rating ": [5, 4, 5, 3, 4, np.nan]
})

Complete the following tasks in order:
	1. Inspect the dataset using .head(), .info() and .describe() where appropriate.
	2. Clean the column names by removing spaces and converting them to lowercase.
	3. Remove unwanted spaces from product and region values and standardise their capitalisation.
	4. Convert units to integers.
	5. Count missing values in each column.
	6. Decide how to handle the missing rating and explain your decision.
	7. Check for duplicate rows and remove them if appropriate.
	8. Create a revenue column by multiplying units by unit price.
	9. Filter the dataset to show sales generating more than £500.
	10. Sort the dataset by revenue, largest first.
	11. Calculate total revenue and average rating.
Explain three data-quality problems you identified and how you addressed them.

In [31]:
import numpy as np
import pandas as pd

sales = pd.DataFrame({
    " Product ": ["Laptop", " Mouse", "LAPTOP", "Keyboard ", "Mouse", "Monitor"],
    " Region ": ["north", "South ", "NORTH", "west", "south", "West "],
    " Units ": ["2", "5", "1", "3", "5", "2"],
    " Unit_Price ": [899, 25, 899, 75, 25, 220],
    " Rating ": [5, 4, 5, 3, 4, np.nan] })

#this is intentionally messy, following the steps above:

#1. Inspect the dataset using .head(), .info() and .describe() where appropriate

sales.head() #mix upper/lower case
sales.info() #1 null in rating
sales.describe() #1 float, 1 int, 3 object columns
sales.isna() #null is the 6th value in rating

#2. Clean the column names by removing spaces and converting them to lowercase

sales.columns = sales.columns.str.lower()
sales.columns = sales.columns.str.strip()

#3. Remove unwanted spaces from product and region values and standardise their capitalisation

sales["product"] = sales["product"].str.strip().str.title()
sales["region"] = sales["region"].str.strip().str.title()

#4. Convert units to integers.

sales["units"] = sales["units"].astype(int)

#5. Count missing values in each column

sales.isna().sum() #1 in rating

#6. Decide how to handle the missing rating and explain your decision
#you can have a rating of 0 so 0 in this case would mean something
#decided to drop row with missing value to avoid misrepresentation

sales = sales.dropna(subset=["rating"])
#subset tells which column to look at for missing values, dropna removes

#7. Check for duplicate rows and remove them if appropriate.

sales.duplicated().sum() #1 duplicated row
sales[sales.duplicated(keep=False)] #displays duplicated, false shows all occurrances of duplicated rows
#rows are exactly the same in every column, choose to drop
sales = sales.drop_duplicates()

#8. Create a revenue column by multiplying units by unit price.

sales["revenue"] = sales["units"]*sales["unit_price"]
print(sales)

#9. Filter the dataset to show sales generating more than £500

sales.query("revenue > 500")

#10. Sort the dataset by revenue, largest first

sales.sort_values(["revenue"], ascending = False)

#11.Calculate total revenue and average rating

sales.revenue.sum() #3047
sales.rating.mean() #4.25

#explain three data quality problems:
#1 - missing data in rating, row removed
#2 - whitespace in many values with mixed upper/lower cases, removed space and made all lowercase
#3 - 'units' wasn't classed as integer but were strings, converted to int

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0    Product      6 non-null      object
 1    Region       6 non-null      object
 2    Units        6 non-null      object
 3    Unit_Price   6 non-null      int64
 4    Rating       5 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 372.0+ bytes
    product region  units  unit_price  rating  revenue
0    Laptop  North      2         899     5.0     1798
1     Mouse  South      5          25     4.0      125
2    Laptop  North      1         899     5.0      899
3  Keyboard   West      3          75     3.0      225

np.float64(4.25)